USE [master]
GO

/****** Object:  Database [OnlineStore]    Script Date: 11/16/2019 11:04:47 PM ******/
CREATE DATABASE [OnlineStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OnlineStore', FILENAME = N'C:\SQL2019RC1\RC1\MSSQL15.MSSQLSERVER\MSSQL\DATA\OnlineStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OnlineStore_log', FILENAME = N'C:\SQL2019RC1\RC1\MSSQL15.MSSQLSERVER\MSSQL\DATA\OnlineStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnlineStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OnlineStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OnlineStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OnlineStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OnlineStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OnlineStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [OnlineStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OnlineStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OnlineStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OnlineStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OnlineStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OnlineStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OnlineStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OnlineStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OnlineStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OnlineStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OnlineStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OnlineStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OnlineStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OnlineStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OnlineStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OnlineStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OnlineStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OnlineStore] SET RECOVERY FULL 
GO

ALTER DATABASE [OnlineStore] SET  MULTI_USER 
GO

ALTER DATABASE [OnlineStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OnlineStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OnlineStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OnlineStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OnlineStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OnlineStore] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OnlineStore] SET  READ_WRITE 
GO

